name: RNS build and deploy

on:
  push:
    branches: [ main ]

jobs:
  testnet_build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node 20
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn

    - name: Build site
      run: |
        export REACT_APP_GIT_HASH=${{ github.sha }}
        yarn build:testnet

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TESTNET_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TESTNET_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.TESTNET_AWS_REGION }}

    - name: Deploy site to S3
      run: |
        aws s3 sync --delete --only-show-errors build/ ${{ secrets.TESTNET_S3_BUCKET }}

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.TESTNET_CLOUDFRONT_DISTRIBUTION }} --paths "/*"

  mainnet_build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node 20
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn

    - name: Build site
      run: |
        export REACT_APP_GIT_HASH=${{ github.sha }}
        yarn build:mainnet

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MAINNET_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.MAINNET_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.MAINNET_AWS_REGION }}

    - name: Deploy site to S3
      run: |
        aws s3 sync --delete --only-show-errors build/ ${{ secrets.MAINNET_S3_BUCKET }}

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.MAINNET_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
